site_name: PostgreSQL Server
site_url: https://gperdrizet.github.io/posgreSQL-server/
repo_url: https://github.com/gperdrizet/posgreSQL-server
repo_name: gperdrizet/posgreSQL-server

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup guide: setup.md
  - Architecture: architecture.md
  - Blog: blog-post.md
